export const page={
  page:46,chapter:18,kicker:'פרק 18 · תחומי חיוביות ושליליות',title:'מתי ערך הפונקציה חיובי?',subtitle:'מוצאים אפס → בודקים צד → כותבים תחום',
  rule:'פונקציה חיובית במקום שבו ערך ה־`y` שלה גדול מ־0. קודם מוצאים היכן הפונקציה מתאפסת, כלומר היכן `y=0`, ואז קובעים באיזה צד של נקודת האפס ערכי ה־`y` חיוביים.',
  sourceRefs:['razpages:bank.json positivity-negativity','official:linear:8','SOURCE_OF_TRUTH.md#9'],
  questions:[
    {id:'PZ01-P46-Q1',family:'PZ01',level:2,responseSpace:'mixed',stem:'נתונה הפונקציה `y=-2x+3`. מצאו תחילה את נקודת האפס של הפונקציה.',subparts:[{text:'הציבו `y=0` וכתבו את המשוואה שמתקבלת.',responseSpace:'equation'},{text:'פתרו ומצאו את ערך `x` שבו הפונקציה מתאפסת.',responseSpace:'lines-2'},{text:'כתבו את נקודת החיתוך עם ציר `x` כזוג סדור.',responseSpace:'short'}],sourceRef:'official:linear:8 — מציאת חיתוך עם ציר x באמצעות פתרון משוואה ממעלה ראשונה',adaptation:'תרגיל מדורג למציאת נקודת אפס לפני קביעת תחום חיוביות.',mathModel:{standard:{A:2,B:1,C:3},expected:{m:-2,b:3,xIntercept:[3,2]},probes:[{x:0,expectedY:3},{x:[3,2],expectedY:0}]}},
    {id:'PZ01-P46-Q2',family:'PZ01',level:3,responseSpace:'mixed',stem:'עבור `y=-2x+3`, קבעו באיזה צד של `x=3/2` ערכי הפונקציה חיוביים.',subparts:[{text:'בדקו ערך פשוט משמאל ל־`3/2`, למשל `x=0`. מהו ערך ה־`y`?',responseSpace:'short'},{text:'האם ערך ה־`y` שקיבלתם חיובי?',responseSpace:'choice-mark',choices:['כן','לא']},{text:'כתבו את תחום ערכי `x` שעבורם ערך הפונקציה חיובי.',responseSpace:'equation'}],sourceRef:'razpages:bank.json positivity-negativity — קביעת תחום חיוביות לפי נקודת האפס; מספרים שונו',adaptation:'נוסף ערך בדיקה פשוט לחיזוק משמעות החיוביות.'},
    {id:'PZ02-P46-Q3',family:'PZ02',level:4,responseSpace:'mixed',stem:'הציגו את אותה מסקנה בדרך גרפית.',graph:{xMin:-2,xMax:4,yMin:-5,yMax:7,xTick:1,yTick:1,showCoordinates:false,ariaLabel:'מערכת צירים לשרטוט הישר y שווה מינוס 2x ועוד 3',lines:[{through:[[0,3],[1,1]]}],points:[{x:1.5,y:0,label:'A'}]},subparts:[{text:'סמנו על הגרף את החלק שבו הישר נמצא מעל ציר `x`.',responseSpace:'graph-draw'},{text:'השלימו: כאשר הגרף מעל ציר `x`, ערך ה־`y` ______ מ־0.',responseSpace:'short'},{text:'כתבו שוב את תחום החיוביות.',responseSpace:'equation'}],sourceRef:'razpages:bank.json positivity-negativity — פירוש גרפי של תחום חיוביות',adaptation:'קישור בין התחום האלגברי למיקום הגרף מעל ציר x.'},
    {id:'PZ03-P46-Q4',family:'PZ03',level:5,responseSpace:'lines-2',stem:'עדיין עבור `y=-2x+3`: כתבו את תחום ערכי `x` שעבורם ערך הפונקציה שלילי, והסבירו כיצד הוא נובע מתחום החיוביות שמצאתם.',sourceRef:'razpages:bank.json positivity-negativity — תחומי חיוביות ושליליות של פונקציה קווית',adaptation:'משלים את תחום החיוביות בתחום השליליות על אותה פונקציה.'},
    {id:'PZ04-P46-Q5',family:'PZ04',level:6,responseSpace:'mixed',stem:'נתונה הפונקציה `y=2x-6`, ונקודת האפס שלה היא `x=3`.',subparts:[{text:'כתבו את תחום ערכי `x` שעבורם הפונקציה חיובית.',responseSpace:'equation'},{text:'כתבו את תחום ערכי `x` שעבורם הפונקציה שלילית.',responseSpace:'equation'}],sourceRef:'razpages:bank.json positivity-negativity — תחומי חיוביות ושליליות לפונקציה עולה; מספרים שונו',adaptation:'וריאציה עם שיפוע חיובי לחיזוק ההבחנה בין עולה ליורד; מספרים שונו.'}
  ]
};
