export const page={
  page:47,
  chapter:19,
  kicker:'פרק 19 · אי־שוויונות קוויים',
  title:'האם המספר הוא פתרון של אי־השוויון?',
  subtitle:'מציבים → בודקים אם הטענה נכונה → קובעים תחום',
  rule:'מספר הוא פתרון של אי־שוויון אם לאחר שמציבים אותו במקום `x` מתקבלת טענה נכונה.',
  sourceRefs:['jerusalem2:src/content/curriculum/idkun-algebri-8.json#page-81-tamar-inequality','jerusalem2:src/content/curriculum/idkun-algebri-8.json#page-84-questions-5-7','jerusalem2:src/content/curriculum/idkun-algebri-8.json#page-18-fuel-thresholds'],
  questions:[
    {id:'IN01-P47-Q1',family:'IN01',level:2,responseSpace:'mixed',stem:'נתון אי־השוויון `-4x<12`.',subparts:[{text:'הציבו `x=1`. האם מתקבלת טענה נכונה?',responseSpace:'choice-mark',choices:['כן','לא']},{text:'הסבירו במילים מדוע כל מספר חיובי הוא פתרון של אי־השוויון.',responseSpace:'lines-2'}],sourceRef:'jerusalem2:src/content/curriculum/idkun-algebri-8.json, page 84, question 6 — explain without solving why every positive number solves -4x<12',adaptation:'נוסף קודם מקרה בדיקה אחד, ולאחריו נשמרה דרישת המקור להסבר כללי ללא פתרון אלגברי.'},
    {id:'IN01-P47-Q2',family:'IN01',level:3,responseSpace:'mixed',stem:'עדיין באי־השוויון `-4x<12`.',subparts:[{text:'תנו דוגמה למספר שלילי שהוא פתרון של אי־השוויון.',responseSpace:'short'},{text:'בדקו את המספר שבחרתם בעזרת הצבה.',responseSpace:'lines-2'}],sourceRef:'jerusalem2:src/content/curriculum/idkun-algebri-8.json, page 84, question 6(b) — give an example of a negative number that is a solution of -4x<12',adaptation:'נשמרה שאלת המקור ונוסף מקום מפורש לבדיקת ההצבה.'},
    {id:'IN02-P47-Q3',family:'IN02',level:4,responseSpace:'mixed',stem:'נתון אי־השוויון `3x>-4`.',subparts:[{text:'תנו דוגמה למספר שהוא פתרון.',responseSpace:'short'},{text:'תנו דוגמה למספר שאינו פתרון.',responseSpace:'short'},{text:'הראו בקצרה בהצבה מדוע הדוגמאות מתאימות.',responseSpace:'lines-2'}],sourceRef:'jerusalem2:src/content/curriculum/idkun-algebri-8.json, page 84, question 7 — give one number that solves 3x>-4 and one that does not',adaptation:'נשמרה שאלת המקור; שטח בדיקת ההצבות צומצם בלבד.'},
    {id:'J2-FUEL-P47-Q4',family:'IN03,IN04',level:5,responseSpace:'mixed',stem:'מחיר ליטר דלק הוא 7 שקלים, כלומר `y=7x`, כאשר `x` היא כמות הדלק בליטרים.',subparts:[{label:'א.',text:'עבור אילו כמויות של דלק העלות גבוהה מ־70 שקלים? כתבו את התחום.',responseSpace:'equation'},{label:'ב.',text:'עבור אילו כמויות של דלק העלות נמוכה מ־35 שקלים? כתבו את התחום.',responseSpace:'equation'}],mathModel:{standard:{A:7,B:-1,C:0},expected:{m:7,b:0,xIntercept:0},probes:[{x:10,expectedY:70},{x:5,expectedY:35}]},sourceRef:'jerusalem2:src/content/curriculum/idkun-algebri-8.json, page 18, question 3 — fuel costs 7 shekels per liter; determine quantities with cost above 70 and below 35 and mark the domains on the x-axis',adaptation:'מחיר הדלק ושני הספים נשמרו. הגרף הוסר משום שהקשר y=7x נתון במפורש; התלמיד כותב את אותם תחומים המבוקשים במקור.'},
    {id:'J2-TAMAR-P47-Q5',family:'IN03,IN04',level:6,responseSpace:'mixed',stem:'לתמר היו `300` ש״ח לקניית שק שינה ותרמיל. מחיר שק השינה היה נמוך ב־`120` ש״ח ממחיר התרמיל, והמחיר של שניהם יחד היה קטן מ־`300` ש״ח. נסמן ב־`x` את מחיר התרמיל.',subparts:[{label:'א.',text:'כתבו אי־שוויון המתאים לכל נתוני השאלה.',responseSpace:'equation'},{label:'ב.',text:'האם ייתכן שמחיר התרמיל שקנתה תמר היה `215` ש״ח? בדקו בעזרת הצבה ונמקו.',responseSpace:'lines-2'}],sourceRef:'jerusalem2:src/content/curriculum/idkun-algebri-8.json, page 81, question 2 — Tamar has 300 NIS; sleeping bag costs 120 NIS less than backpack; total is below 300; x is backpack price; test whether 215 NIS is possible',adaptation:'כל נתוני המקור נשמרו. סעיף הבחירה באי־השוויון הומר לכתיבת האי־שוויון בעצמו (`x+x-120<300`) כדי לבדוק בניית מודל ולא ניחוש מתוך אפשרויות.'}
  ]
};
