export const page={
  page:41,
  chapter:15,
  kicker:'פרק 15 · ישרים מקבילים לצירים',
  title:'ישר אופקי או ישר אנכי?',
  subtitle:'y=c → מקביל לציר x · x=c → מקביל לציר y · רמות 2–5',
  rule:'הישר `y=c` הוא ישר אופקי המקביל לציר `x`, ושיפועו `0`. הישר `x=c` הוא ישר אנכי המקביל לציר `y`; הוא אינו גרף של פונקציה מהצורה `y=f(x)`.',
  sourceRefs:['razpages:עמוד-444.html','razpages:עמוד-446.html','data/exercise-family-map-phase-1.md'],
  questions:[
    {id:'M08-C06-P41-Q1',family:'M08,C06',level:2,responseSpace:'choice-mark',stem:'לאיזה גרף מתאימה המשוואה `y=-3`? סמנו את הגרף המתאים.',panelsColumns:3,panels:[{responseSpace:'choice-mark',graph:{xMin:-5,xMax:5,yMin:-5,yMax:5,showCoordinates:false,ariaLabel:'ישר אופקי בגובה מינוס שלוש',lines:[{through:[[-5,-3],[5,-3]]}]}},{responseSpace:'choice-mark',graph:{xMin:-5,xMax:5,yMin:-5,yMax:5,showCoordinates:false,ariaLabel:'ישר אנכי באיקס מינוס שלוש',verticalLines:[-3]}},{responseSpace:'choice-mark',graph:{xMin:-5,xMax:5,yMin:-5,yMax:5,showCoordinates:false,ariaLabel:'ישר אופקי בגובה שלוש',lines:[{through:[[-5,3],[5,3]]}]}}],sourceRef:'razpages:עמוד-444.html — לאיזה ישר מתאימה הנוסחה y=-3',adaptation:'שלושת שרטוטי המקור אוחדו לכרטיסי SVG אחידים; המשוואה והרעיון נשמרו בדיוק.'},
    {id:'M08-P41-Q2',family:'M08',level:3,responseSpace:'mixed',stem:'מצאו את משוואת הישר המקביל לציר `x` ועובר דרך הנקודה `(-3,1)`.',subparts:[{text:'הערך הקבוע של `y` הוא',responseSpace:'short'},{text:'מהי משוואת הישר?',responseSpace:'equation'}],sourceRef:'razpages:עמוד-444.html — ישר המקביל לציר x ועובר דרך (-3,1)',adaptation:'נוסף שלב זיהוי y הקבוע לפני כתיבת המשוואה.',mathModel:{standard:{A:0,B:1,C:1},expected:{m:0,b:1},probes:[{point:[-3,1],onLine:true},{point:[4,1],onLine:true},{point:[-3,0],onLine:false}]}},
    {id:'M08-P41-Q3',family:'M08',level:4,responseSpace:'lines-2',stem:'ישר עובר דרך הנקודה `(5,-5)` ושיפועו `0`. כתבו את משוואתו והסבירו מדוע שיעור ה־`x` של הנקודה אינו מופיע במשוואה.',sourceRef:'razpages:עמוד-446.html — ישר העובר דרך (5,-5) ושיפועו 0',adaptation:'נוסף נימוק קצר כדי לקשור בין שיפוע 0 לבין y קבוע.',mathModel:{standard:{A:0,B:1,C:-5},expected:{m:0,b:-5},probes:[{point:[5,-5],onLine:true},{point:[0,-5],onLine:true},{point:[5,0],onLine:false}]}},
    {id:'C06-P41-Q4',family:'C06',level:5,responseSpace:'mixed',stem:'מצאו את משוואת הישר המקביל לציר `y` ועובר דרך הנקודה `(2,0)`.',subparts:[{text:'מהי משוואת הישר?',responseSpace:'equation'},{text:'האם הישר הזה הוא גרף של פונקציה `y=f(x)`? סמנו כן / לא',responseSpace:'choice-mark',answerCount:2},{text:'הסבירו בקצרה מדוע.',responseSpace:'lines-2'}],sourceRef:'razpages:עמוד-446.html — ישר המקביל לציר Y ועובר דרך (2,0)',adaptation:'הניסוח תוקן ל-x=2 והתווסף הקישור למבחן הפונקציה, בהתאם למשפחת C06.',mathModel:{standard:{A:1,B:0,C:2},expected:{xIntercept:2},probes:[{point:[2,0],onLine:true},{point:[2,5],onLine:true},{point:[0,2],onLine:false}]}},
    {id:'M08-C06-P41-Q5',family:'M08,C06',level:5,responseSpace:'mixed',stem:'דרך הנקודה `(-1,7)` מעבירים שני ישרים המקבילים לצירים.',subparts:[{text:'כתבו את משוואת הישר האופקי (המקביל לציר `x`).',responseSpace:'equation'},{text:'כתבו את משוואת הישר האנכי (המקביל לציר `y`).',responseSpace:'equation'},{text:'מהו השיפוע של הישר האופקי שכתבתם?',responseSpace:'short'},{text:'מהי נקודת החיתוך של שני הישרים האלה?',responseSpace:'short'},{text:'האם הנקודה `(-1,2)` ממוקמת על הישר האנכי שכתבתם? סמנו כן / לא',responseSpace:'choice-mark',answerCount:2}],sourceRef:'razpages:עמוד-446.html — ישר המקביל לציר x דרך (-1,7); הורחב גם לישר האנכי דרך אותה נקודה',adaptation:'הנקודה נשמרה בדיוק מן המקור; נוסף הישר האנכי כהרחבה מאותה נקודה.'},
    {id:'C06-P41-Q6',family:'C06',level:6,responseSpace:'lines-2',stem:'נתונים שני הישרים `y=3` ו־`x=-2`. מצאו את נקודת החיתוך שלהם, וכתבו אותה כזוג סדור. הסבירו בקצרה.',sourceRef:'razpages:עמוד-444.html — חיתוך ישר אופקי עם ישר אנכי; מספרים שונו',adaptation:'מרחיב אל חיתוך של ישר אופקי ואנכי; מספרים שונו.'}
  ]
};
